### ISSUE TITLE
How to query related txids for given AccountId

### ISSUE THREAD

**Issue by Astrapolis-peasant** [iclighthouse/DRC_standards#5]
Hi,
I am reading DRC20 code and trying to figure out the way to fetch related txids given AccoundId. In ethereum, since its MPT takes care of searching txids by address. How is is implemented in DRC20. DRC202 allows checking txnrecord by txid. How txids can then be fetched

**Comment by iclighthouse** [comment]
https://github.com/iclighthouse/DRC_standards/blob/main/DRC202/examples/IClighthouse/lib/DRC202.mo

```
public func generateTxid(_canister: Principal, _caller: AccountId, _nonce: Nat): Txid{
    let canister: [Nat8] = Blob.toArray(Principal.toBlob(_canister));
    let caller: [Nat8] = Blob.toArray(_caller);
    let nonce: [Nat8] = Binary.BigEndian.fromNat32(Nat32.fromNat(_nonce));
    let txInfo = Array.append(Array.append(canister, caller), nonce);
    let h224: [Nat8] = SHA224.sha224(txInfo);
    return Blob.fromArray(Array.append(nonce, h224));
};
```
_canister: Principal, token canister-id
